server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_springboot?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "NyeqozuvZh3ejFvvDlJjNqtkkYTdG33GkK5pN72qH1vMz7k5vkpVH9KAkZKxbLVg";